# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  2048_config = debug

else ifeq ($(config),release)
  2048_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := 2048

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

2048:
ifneq (,$(2048_config))
	@echo "==== Building 2048 ($(2048_config)) ===="
	@${MAKE} --no-print-directory -C . -f 2048.make config=$(2048_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f 2048.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   2048"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"